name = "MindResearchRepository"
uuid = "59da8ea2-18e2-11e9-3c37-393f9c147fd2"
authors = ["Douglas Bates <dmbates@gmail.com>"]
version = "0.1.0"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
